module.exports = {
    commands: {
        APP_SHOW_TIMEFRAME_OPTIONS: 'APP_SHOW_TIMEFRAME_OPTIONS',
        APP_HIDE_DURATION_OPTIONS: 'APP_HIDE_TIMEFRAME_OPTIONS',
        APP_SHOW_DURATION_OPTIONS: 'APP_SHOW_TIMEFRAME_OPTIONS',
        APP_HIDE_DURATION_OPTIONS: 'APP_HIDE_TIMEFRAME_OPTIONS',

        CHART_UPDATE_TICKER: 'CHART_CHANGE_TICKER',
        CHART_UPDATE_DURATION: 'CHART_UPDATE_DURATION',
        CHART_UPDATE_TIMEFRAME: 'CHART_UPDATE_TIMEFRAME',
        CHART_UPDATE_ACTIVECHART: 'CHART_UPDATE_ACTIVECHART',
        CHART_UPDATE_LAYOUT: 'CHART_UPDATE_LAYOUT',
        CHART_PREVIEW_PLAY: 'CHART_PREVIEW_PLAY',
        CHART_PREVIEW_PAUSE: 'CHART_PREVIEW_PAUSE',
        CHART_PREVIEW_STOP: 'CHART_PREVIEW_STOP'
    }
}